# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: "**/packages.lock.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |-
        export ROOTDIR=$(pwd);
        mkdir $ROOTDIR/bundles;
        for t in "win-x64" "linux-x64" "linux-musl-x64" "linux-arm64" "linux-musl-arm64"; do
          dotnet build src/Indexer.vbproj --configuration Release --no-restore --runtime $t --no-self-contained;
          cd src/bin/Release/net8.0/$t;
          zip -r $ROOTDIR/bundles/indexer-$t.zip *;
          cd -;
        done;
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bundles/indexer-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
